import { Book, Bundle } from './types';

export const BOOKS: Book[] = [
  {
    id: '1',
    title: 'Atomic Habits',
    author: 'James Clear',
    price: 3500,
    image: 'https://m.media-amazon.com/images/I/91bYsX41DVL._AC_UF1000,1000_QL80_.jpg',
    description: 'An easy and proven way to build good habits and break bad ones.',
    category: 'Productivity',
    whoIsItFor: ['Entrepreneurs', 'Students', 'Anyone looking to improve'],
    keyTakeaways: ['Small changes lead to big results', 'Focus on systems, not goals', 'Identity-based habits'],
    isBestSeller: true,
  },
  {
    id: '2',
    title: 'Essentialism',
    author: 'Greg McKeown',
    price: 3800,
    image: 'https://m.media-amazon.com/images/I/71X8X8-S3UL._AC_UF1000,1000_QL80_.jpg',
    description: 'The disciplined pursuit of less.',
    category: 'Productivity',
    whoIsItFor: ['Busy professionals', 'Leaders', 'Overwhelmed individuals'],
    keyTakeaways: ['Less but better', 'The power of choice', 'The discipline of elimination'],
    isBestSeller: true,
  },
  {
    id: '3',
    title: 'Feel Good Productivity',
    author: 'Ali Abdaal',
    price: 4200,
    image: 'https://m.media-amazon.com/images/I/71u9S+X9X+L._AC_UF1000,1000_QL80_.jpg',
    description: 'How to do more of what matters to you.',
    category: 'Productivity',
    whoIsItFor: ['Knowledge workers', 'Creatives', 'Ambitious professionals'],
    keyTakeaways: ['Play is the ultimate productivity hack', 'Power of small wins', 'Focus on the process'],
    isBestSeller: true,
  },
  {
    id: '4',
    title: 'Can\'t Hurt Me',
    author: 'David Goggins',
    price: 4500,
    image: 'https://m.media-amazon.com/images/I/81g8T-0D+9L._AC_UF1000,1000_QL80_.jpg',
    description: 'Master your mind and defy the odds.',
    category: 'Mindset',
    whoIsItFor: ['Athletes', 'Entrepreneurs', 'Anyone facing adversity'],
    keyTakeaways: ['The 40% rule', 'Callous your mind', 'Taking souls'],
    isBestSeller: true,
  },
  {
    id: '5',
    title: 'Dopamine Detox',
    author: 'Thibaut Meurisse',
    price: 2800,
    image: 'https://m.media-amazon.com/images/I/61S8vV+Q+SL._AC_UF1000,1000_QL80_.jpg',
    description: 'A simple guide to eliminate distractions and train your brain to do hard things.',
    category: 'Productivity',
    whoIsItFor: ['Distracted individuals', 'Students', 'Focus seekers'],
    keyTakeaways: ['Identify dopamine triggers', 'The power of boredom', 'Deep work habits'],
  },
  {
    id: '6',
    title: 'The Diary of a CEO',
    author: 'Steven Bartlett',
    price: 4800,
    image: 'https://m.media-amazon.com/images/I/71p+8v+8+SL._AC_UF1000,1000_QL80_.jpg',
    description: 'The 33 laws of business and life.',
    category: 'Business',
    whoIsItFor: ['Founders', 'Leaders', 'Aspiring entrepreneurs'],
    keyTakeaways: ['The law of the first 5 minutes', 'The power of story', 'The importance of culture'],
    isBestSeller: true,
  },
  {
    id: '7',
    title: 'Million Dollar Weekend',
    author: 'Noah Kagan',
    price: 3900,
    image: 'https://m.media-amazon.com/images/I/71p+8v+8+SL._AC_UF1000,1000_QL80_.jpg',
    description: 'The surprisingly simple way to launch a 7-figure business in 48 hours.',
    category: 'Business',
    whoIsItFor: ['Aspiring founders', 'Side hustlers', 'Action takers'],
    keyTakeaways: ['The "Now" habit', 'Ask for what you want', 'Validate before building'],
  },
];

export const BUNDLES: Bundle[] = [
  {
    id: 'b1',
    title: 'The Founder Starter Pack',
    books: [BOOKS[5], BOOKS[6]],
    price: 7500,
    originalPrice: 8700,
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=1000',
    description: 'Everything you need to start your journey from zero to one with a lean mindset.',
  },
  {
    id: 'b2',
    title: 'The Productivity Masterclass',
    books: [BOOKS[0], BOOKS[2]],
    price: 6500,
    originalPrice: 7700,
    image: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?auto=format&fit=crop&q=80&w=1000',
    description: 'Master your habits and your focus to achieve deep work every single day.',
  },
  {
    id: 'b3',
    title: 'The Mindset Shift',
    books: [BOOKS[3], BOOKS[4]],
    price: 6200,
    originalPrice: 7300,
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=1000',
    description: 'Build mental toughness and eliminate distractions to reach your full potential.',
  },
];
